# This file is generated by 'nixos-generate-config' during installation.
# Run: nixos-generate-config --root /mnt
# Then copy /mnt/etc/nixos/hardware-configuration.nix here before building.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Filesystem and swap configuration will be populated by nixos-generate-config.
  # Replace this file with the generated one after partitioning your disk.

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
