background = #211414
foreground = #DAD5D8
cursor-color = #D76725
selection-background = #697A94
selection-foreground = #211414

palette = 0=#29292A
palette = 1=#741106
palette = 2=#697A94
palette = 3=#D76725
palette = 4=#0D2364
palette = 5=#CC9C97
palette = 6=#697A94
palette = 7=#DAD5D8
palette = 8=#353334
palette = 9=#9B1A10
palette = 10=#7D8EA5
palette = 11=#E07C35
palette = 12=#1A3A96
palette = 13=#D4ABA8
palette = 14=#7D8EA5
palette = 15=#E8E4E7
