# Background and foreground colors
background = #0E0B09
foreground = #ffffff

# Standard colors
palette = 0=#0E0B09
palette = 1=#ea3e44
palette = 2=#72c5bd
palette = 3=#C4BAAD
palette = 4=#BBBCC2
palette = 5=#b7aeb5
palette = 6=#a7c2cd
palette = 7=#DCD5CB

# Bright colors
palette = 8=#8c7c71
palette = 9=#f88c90
palette = 10=#b1e2dd
palette = 11=#ebe7e2
palette = 12=#ebecee
palette = 13=#e2dee2
palette = 14=#e1ebef
palette = 15=#ffffff
