$color = rgba(14, 11, 9, 1)
$inner_color = rgba(14, 11, 9, 0.66)
$outer_color = rgba(183, 174, 181, 1)
$font_color = rgba(255, 255, 255, 1)
$placeholder_color = rgba(255, 255, 255, 0.7)
$check_color = rgba(167, 194, 205, 1)
