background            #0E0B09
foreground            #ffffff

# black
color0  #0E0B09
color8  #8c7c71

# red
color1  #ea3e44
color9  #f88c90

# green
color2  #72c5bd
color10 #b1e2dd

# yellow
color3  #C4BAAD
color11 #ebe7e2

# blue
color4  #BBBCC2
color12 #ebecee

# magenta
color5  #b7aeb5
color13 #e2dee2

#cyan
color6  #a7c2cd
color14 #e1ebef

#white
color7  #DCD5CB
color15 #ffffff


